// ⚠️ Auto-generated by scripts/generate-gallery-data.js
// Do not edit manually.

export interface GalleryImage {
  id: number;
  src: string;
  alt: string;
  width: number;
  height: number;
}

const galleryData: GalleryImage[] = [
  {
    "id": 1,
    "src": "/gallery-imgs/_img-1.webp",
    "alt": " img 1",
    "width": 750,
    "height": 1334
  },
  {
    "id": 2,
    "src": "/gallery-imgs/_img-10.webp",
    "alt": " img 10",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 3,
    "src": "/gallery-imgs/_img-11.webp",
    "alt": " img 11",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 4,
    "src": "/gallery-imgs/_img-12.webp",
    "alt": " img 12",
    "width": 1200,
    "height": 1600
  },
  {
    "id": 5,
    "src": "/gallery-imgs/_img-14.webp",
    "alt": " img 14",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 6,
    "src": "/gallery-imgs/_img-15.webp",
    "alt": " img 15",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 7,
    "src": "/gallery-imgs/_img-16.webp",
    "alt": " img 16",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 8,
    "src": "/gallery-imgs/_img-17.webp",
    "alt": " img 17",
    "width": 750,
    "height": 1334
  },
  {
    "id": 9,
    "src": "/gallery-imgs/_img-18.webp",
    "alt": " img 18",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 10,
    "src": "/gallery-imgs/_img-19.webp",
    "alt": " img 19",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 11,
    "src": "/gallery-imgs/_img-2.webp",
    "alt": " img 2",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 12,
    "src": "/gallery-imgs/_img-20.webp",
    "alt": " img 20",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 13,
    "src": "/gallery-imgs/_img-21.webp",
    "alt": " img 21",
    "width": 1200,
    "height": 1600
  },
  {
    "id": 14,
    "src": "/gallery-imgs/_img-22.webp",
    "alt": " img 22",
    "width": 1600,
    "height": 1200
  },
  {
    "id": 15,
    "src": "/gallery-imgs/_img-23.webp",
    "alt": " img 23",
    "width": 1202,
    "height": 1600
  },
  {
    "id": 16,
    "src": "/gallery-imgs/_img-24.webp",
    "alt": " img 24",
    "width": 1600,
    "height": 1200
  },
  {
    "id": 17,
    "src": "/gallery-imgs/_img-25.webp",
    "alt": " img 25",
    "width": 1200,
    "height": 1600
  },
  {
    "id": 18,
    "src": "/gallery-imgs/_img-26.webp",
    "alt": " img 26",
    "width": 1200,
    "height": 1600
  },
  {
    "id": 19,
    "src": "/gallery-imgs/_img-27.webp",
    "alt": " img 27",
    "width": 1200,
    "height": 1600
  },
  {
    "id": 20,
    "src": "/gallery-imgs/_img-28.webp",
    "alt": " img 28",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 21,
    "src": "/gallery-imgs/_img-29.webp",
    "alt": " img 29",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 22,
    "src": "/gallery-imgs/_img-3.webp",
    "alt": " img 3",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 23,
    "src": "/gallery-imgs/_img-30.webp",
    "alt": " img 30",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 24,
    "src": "/gallery-imgs/_img-31.webp",
    "alt": " img 31",
    "width": 5184,
    "height": 3456
  },
  {
    "id": 25,
    "src": "/gallery-imgs/_img-32.webp",
    "alt": " img 32",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 26,
    "src": "/gallery-imgs/_img-33.webp",
    "alt": " img 33",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 27,
    "src": "/gallery-imgs/_img-34.webp",
    "alt": " img 34",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 28,
    "src": "/gallery-imgs/_img-35.webp",
    "alt": " img 35",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 29,
    "src": "/gallery-imgs/_img-36.webp",
    "alt": " img 36",
    "width": 5184,
    "height": 3456
  },
  {
    "id": 30,
    "src": "/gallery-imgs/_img-37.webp",
    "alt": " img 37",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 31,
    "src": "/gallery-imgs/_img-38.webp",
    "alt": " img 38",
    "width": 3456,
    "height": 5184
  },
  {
    "id": 32,
    "src": "/gallery-imgs/_img-4.webp",
    "alt": " img 4",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 33,
    "src": "/gallery-imgs/_img-5.webp",
    "alt": " img 5",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 34,
    "src": "/gallery-imgs/_img-6.webp",
    "alt": " img 6",
    "width": 1496,
    "height": 1496
  },
  {
    "id": 35,
    "src": "/gallery-imgs/_img-7.webp",
    "alt": " img 7",
    "width": 1496,
    "height": 1496
  },
  {
    "id": 36,
    "src": "/gallery-imgs/_img-8.webp",
    "alt": " img 8",
    "width": 1536,
    "height": 2048
  },
  {
    "id": 37,
    "src": "/gallery-imgs/_img-9.webp",
    "alt": " img 9",
    "width": 1536,
    "height": 2048
  }
];

export default galleryData;
